first, get libraries

In [2]:
import numpy
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
df = pd.read_csv('data.csv', error_bad_lines=False)

In [31]:
df #imported dataset

,externalId,classificationOfInstructionalProgramCode,courseNumber,courseTitle,subjectAbbreviation,departmentExternalId,institutionExternalId,facilityExternalId,description
0,ABROAD HM,NaN,ABROAD HM,Semester Abroad,HMID,HMID,HM,HM,Placeholder course for students studying abroa...
1,ABUS300A CG,NaN,ABUS300A CG,Intro to Art Market Dynamics,GACM,GACM,CG,CG,NaN
2,ABUS300C CG,NaN,ABUS300C CG,Contemporary Art Markets,GACM,GACM,CG,CG,"A partner course to Art Market Dynamics, Conte..."
3,ABUS301 CG,NaN,ABUS301 CG,Legal Foundations Creative Indus,GACM,GACM,CG,CG,NaN
4,ABUS304A CG,NaN,ABUS304A CG,The Gallery Business,GACM,GACM,CG,CG,The Fundamentals of an Art Gallery is a detail...
...,...,...,...,...,...,...,...,...,...
14595,XSPA190 CM,NaN,XSPA190 CM,Senior Thesis in Spanish,MMOD,MMOD,CM,CM,NaN
14596,XSPA190A CM,NaN,XSPA190A CM,Senior Thesis in Spanish,MMOD,MMOD,CM,CM,NaN
14597,XSPA190B CM,NaN,XSPA190B CM,Senior Thesis in Spanish,MMOD,MMOD,CM,CM,NaN
14598,XSPA191 CM,NaN,XSPA191 CM,Senior Research in Spanish,MMOD,MMOD,CM,CM,NaN
14599,XSPA192 CM,NaN,XSPA192 CM,Senior Thesis in Spanish,MMOD,MMOD,CM,CM,NaN

In [32]:
#drop columns that aren't important: classificationOfInstructionalProgramCode, externalId (same as courseNumber), subjectAbbreviation, dsubjectAbbreviation, same as departmentExternalId, institutionExternalId (same as facilityExternalId)
df.drop(['externalId', 'classificationOfInstructionalProgramCode', 'subjectAbbreviation', 'departmentExternalId', 'institutionExternalId'],  axis=1, inplace=True)

In [ ]:
#rename columns to be more helpful
df = df.rename(columns={"courseNumber": "Course Number", "courseTitle": "Course Title", "facilityExternalId": "Campus", "description" : "Description"})

In [47]:
#see all the na's 
df.isna().sum()

Course Number     117
CourseTitle       125
Campus            168
Description      4077
dtype: int64