In [7]:
import pandas as pd

data = pd.read_json ("data_5scheduler.json")
data

,title,identifier,description,source,credits,instructors,offered,prerequisites,corequisites,currently_offered,fee
0,Introduction to American Cultures,AMST-103-HM,An interdisciplinary introduction to principal...,HarveyMudd,300,[Staff],,,,False,0
1,Print and American Culture,AMST-115-HM,Covers numerous developments in American print...,HarveyMudd,300,[Anup Gampa],,,,True,0
2,Hyphenated Americans,AMST-120-HM,A focus on the experience of immigrants in the...,HarveyMudd,300,[Balseiro],,,,False,0
3,"Life: Knowledge, Belief, and Cultural Practices",ANTH-110-HM,An exploration of cultural attitudes toward li...,HarveyMudd,300,[de Laet],,,,False,0
4,Introduction to the Anthropology of Science an...,ANTH-111-HM,An introduction to science and technology as c...,HarveyMudd,300,[Marianne De Laet],,,,True,0
...,...,...,...,...,...,...,...,...,...,...,...
4438,Autobiography and Memoir,WRIT-126-PZ,This course will look at the writer’s life as ...,Pitzer,0,[],,,,False,0
4439,Writing the Senior Thesis,WRIT-195-PZ,This course will guide you through the process...,Pitzer,0,[],,,,False,0
4440,IGLAS Seminar,GLAS-185-PZ,,Pitzer,0,[],,,,False,0
4441,Global Local Research Workshop,GLAS-19-4A,,Pitzer,0,[],,,,False,0
4442,Global Local Teaching Workshop,GLAS-19-4B,,Pitzer,0,[],,,,False,0

In [9]:
data.loc[data["fee"] > 0]

,title,identifier,description,source,credits,instructors,offered,prerequisites,corequisites,currently_offered,fee
9,Photography,ART-033-HM,Approaching the medium from an artistic perspe...,HarveyMudd,300,[Fandell],,ART002 HM,,False,150
199,Building Los Angeles,EA-174-HM,This course explores the complex network of ur...,HarveyMudd,300,[Groves],,,,False,50
287,Digital Cinema: Experimental Animation,MS-170-HM,"Intermediate/advanced video course, exploring ...",HarveyMudd,300,[Katherine Breeden],,MS182 HM,,True,75
290,Introduction to Video Art,MS-182-HM,This course is an introduction to video art th...,HarveyMudd,300,[Mayeri],,MS 049 PO or MS 049 PZ or MS 049 SC or MS 051 ...,,False,75
4173,College Inside-Out,ORST-161-PZ,College Inside-Out represents some of our grea...,Pitzer,100,[Barbara Junisbai],,,,True,15

In [14]:
len(data.loc[data["fee"] = 0])

SyntaxError: invalid syntax (4016629667.py, line 1)